[package]
name = "algorithms-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
peak_alloc = "0.3.0"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
sysinfo = "0.37.0"
tokio = { version = "1.47.1", features = ["full"] }
tower = "0.5.2"
